<?php
/**
 * dev/make-fixtures.php
 *
 * Generates small, valid sample books for the local dev stack.
 *
 * Run INSIDE the Nextcloud container -- it needs ext-zip and ext-gd, both of
 * which nextcloud:34-apache ships. The repo is bind-mounted, so the output
 * lands in ./dev/fixtures on the host. dev/seed.sh does this for you:
 *
 *   docker compose exec --user "$(id -u):$(id -g)" app php \
 *     /var/www/html/custom_apps/koreader_companion/dev/make-fixtures.php \
 *     /var/www/html/custom_apps/koreader_companion/dev/fixtures
 *
 * The EPUBs carry a full Dublin Core metadata block plus an embedded cover, so
 * they exercise BookService::parseEpubOPF() and the EPUB thumbnail path. The
 * PDF has a populated /Info dictionary for smalot/pdfparser.
 *
 * Note: the calibre:series meta below is deliberately included even though
 * parseEpubOPF() does not currently read it -- the app has a `series` column
 * and OPDS series facets, but no EPUB series extraction, so series is always
 * empty for EPUB today. The fixture is ready for when that is fixed.
 */

declare(strict_types=1);

$out = $argv[1] ?? __DIR__ . '/fixtures';
if (!is_dir($out) && !@mkdir($out, 0777, true)) {
    fwrite(STDERR, "cannot create $out\n");
    exit(1);
}

$books = [
    [
        'file'        => 'carroll-alice-in-wonderland.epub',
        'title'       => "Alice's Adventures in Wonderland",
        'author'      => 'Lewis Carroll',
        'language'    => 'en',
        'publisher'   => 'Macmillan and Co.',
        'date'        => '1865-11-26',
        'subject'     => 'Fiction, Fantasy',
        'series'      => 'Wonderland',
        'identifier'  => 'urn:uuid:11111111-1111-4111-8111-111111111111',
        'description' => 'Dev fixture generated by dev/make-fixtures.php.',
        'rgb'         => [0x1f, 0x5f, 0x8b],
    ],
    [
        'file'        => 'kafka-der-prozess.epub',
        'title'       => 'Der Prozess',
        'author'      => 'Franz Kafka',
        'language'    => 'de',
        'publisher'   => 'Verlag Die Schmiede',
        'date'        => '1925-04-26',
        'subject'     => 'Roman',
        'series'      => '',
        'identifier'  => 'urn:uuid:22222222-2222-4222-8222-222222222222',
        'description' => 'Dev fixture generated by dev/make-fixtures.php.',
        'rgb'         => [0x7a, 0x27, 0x2c],
    ],
    [
        'file'   => 'omelette-comics-001.cbz',
        'title'  => 'Omelette Comics #1',
        'author' => 'International Omelette',
        'rgb'    => [0x2c, 0x5f, 0x2e],
        'pages'  => 3,
    ],
    [
        'file'     => 'dev-stack-handbook.pdf',
        'title'    => 'The Dev Stack Handbook',
        'author'   => 'International Omelette',
        'subject'  => 'Documentation',
        'keywords' => 'nextcloud, koreader, opds',
    ],
];

foreach ($books as $b) {
    $path = rtrim($out, '/') . '/' . $b['file'];
    if (str_ends_with($b['file'], '.epub')) {
        write_epub($path, $b);
    } elseif (str_ends_with($b['file'], '.cbz')) {
        write_cbz($path, $b);
    } else {
        write_pdf($path, $b);
    }
    @chmod($path, 0664);
    printf("wrote %s (%d bytes)\n", $path, (int) filesize($path));
}

// ---------------------------------------------------------------------------

function xml(string $s): string {
    return htmlspecialchars($s, ENT_XML1 | ENT_QUOTES, 'UTF-8');
}

/** Flat two-tone cover using GD's built-in bitmap fonts -- no TTF needed. */
function cover_jpeg(string $title, string $author, array $rgb): string {
    $w = 360;
    $h = 540;
    $img = imagecreatetruecolor($w, $h);
    $bg = imagecolorallocate($img, $rgb[0], $rgb[1], $rgb[2]);
    $fg = imagecolorallocate($img, 0xff, 0xff, 0xff);
    imagefilledrectangle($img, 0, 0, $w, $h, $bg);
    imagerectangle($img, 10, 10, $w - 11, $h - 11, $fg);

    $lines = explode("\n", wordwrap($title, 20, "\n", true));
    foreach ($lines as $i => $line) {
        imagestring($img, 5, 28, 70 + $i * 24, $line, $fg);
    }
    imagestring($img, 3, 28, $h - 62, $author, $fg);

    ob_start();
    imagejpeg($img, null, 85);
    return (string) ob_get_clean();
}

function write_epub(string $path, array $b): void {
    @unlink($path);
    $zip = new ZipArchive();
    if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
        throw new RuntimeException("cannot create $path");
    }

    // EPUB requires 'mimetype' first and stored uncompressed.
    $zip->addFromString('mimetype', 'application/epub+zip');
    $zip->setCompressionName('mimetype', ZipArchive::CM_STORE);

    $zip->addFromString('META-INF/container.xml', <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
      <rootfiles>
        <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
      </rootfiles>
    </container>
    XML);

    $id    = xml($b['identifier']);
    $title = xml($b['title']);
    $auth  = xml($b['author']);
    $lang  = xml($b['language']);
    $pub   = xml($b['publisher']);
    $date  = xml($b['date']);
    $subj  = xml($b['subject']);
    $desc  = xml($b['description']);

    $series = '';
    if ($b['series'] !== '') {
        $series = '    <meta name="calibre:series" content="' . xml($b['series']) . '"/>' . "\n"
                . '    <meta name="calibre:series_index" content="1"/>' . "\n";
    }

    $zip->addFromString('OEBPS/content.opf', <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="bookid">
      <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
        <dc:identifier id="bookid">{$id}</dc:identifier>
        <dc:title>{$title}</dc:title>
        <dc:creator opf:role="aut" opf:file-as="{$auth}">{$auth}</dc:creator>
        <dc:language>{$lang}</dc:language>
        <dc:publisher>{$pub}</dc:publisher>
        <dc:date>{$date}</dc:date>
        <dc:subject>{$subj}</dc:subject>
        <dc:description>{$desc}</dc:description>
        <meta name="cover" content="cover-image"/>
    {$series}  </metadata>
      <manifest>
        <item id="cover-image" href="cover.jpg" media-type="image/jpeg"/>
        <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
        <item id="ch1" href="chapter1.xhtml" media-type="application/xhtml+xml"/>
      </manifest>
      <spine toc="ncx">
        <itemref idref="ch1"/>
      </spine>
    </package>
    XML);

    $zip->addFromString('OEBPS/toc.ncx', <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
      <head><meta name="dtb:uid" content="{$id}"/></head>
      <docTitle><text>{$title}</text></docTitle>
      <navMap>
        <navPoint id="np1" playOrder="1">
          <navLabel><text>Chapter 1</text></navLabel>
          <content src="chapter1.xhtml"/>
        </navPoint>
      </navMap>
    </ncx>
    XML);

    $zip->addFromString('OEBPS/chapter1.xhtml', <<<XML
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head><title>{$title}</title></head>
      <body>
        <h1>{$title}</h1>
        <p>{$desc}</p>
      </body>
    </html>
    XML);

    $zip->addFromString('OEBPS/cover.jpg', cover_jpeg($b['title'], $b['author'], $b['rgb']));
    $zip->close();
}

/** PDF literal strings are ASCII; escape parentheses and backslashes. */
/**
 * Comic archive: numbered page images, deliberately written to the zip in
 * REVERSE order so the provider has to sort them. Archive order alone would
 * hand back the last page as the cover.
 */
function write_cbz(string $path, array $b): void {
    @unlink($path);
    $zip = new ZipArchive();
    if ($zip->open($path, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
        throw new RuntimeException("cannot create $path");
    }

    $pages = $b['pages'] ?? 3;
    for ($i = $pages; $i >= 1; $i--) {
        $label = $i === 1 ? $b['title'] : 'Page ' . $i;
        // Single-digit names on purpose: natural sort must keep 2 before 10.
        $zip->addFromString(sprintf('page%d.jpg', $i), cover_jpeg($label, $b['author'], $b['rgb']));
    }
    // Noise a real archive would carry, which must not be mistaken for page one.
    $zip->addFromString('__MACOSX/._page1.jpg', 'resource fork junk');
    // A fuller ComicInfo.xml so parseComicInfoXml() is actually exercised: series,
    // issue number, writer, publisher and summary, not just a series name.
    $zip->addFromString('ComicInfo.xml', <<<XML
    <?xml version="1.0" encoding="utf-8"?>
    <ComicInfo>
      <Series>Omelette Comics</Series>
      <Number>1</Number>
      <Writer>{$b['author']}</Writer>
      <Publisher>International Omelette Press</Publisher>
      <Summary>Dev fixture generated by dev/make-fixtures.php.</Summary>
      <Year>2026</Year>
    </ComicInfo>
    XML);
    $zip->close();
}

function pdf_str(string $s): string {
    $s = (string) preg_replace('/[^\x20-\x7E]/', '', $s);
    return addcslashes($s, "()\\");
}

function write_pdf(string $path, array $b): void {
    $text = "BT /F1 24 Tf 72 760 Td (" . pdf_str($b['title']) . ") Tj ET\n"
          . "BT /F1 14 Tf 72 730 Td (" . pdf_str($b['author']) . ") Tj ET\n"
          . "BT /F1 11 Tf 72 700 Td (Dev fixture generated by dev/make-fixtures.php) Tj ET";

    $objects = [
        1 => '<< /Type /Catalog /Pages 2 0 R >>',
        2 => '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
        3 => '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] '
             . '/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
        4 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        5 => '<< /Length ' . strlen($text) . " >>\nstream\n" . $text . "\nendstream",
        6 => '<< /Title (' . pdf_str($b['title']) . ') '
             . '/Author (' . pdf_str($b['author']) . ') '
             . '/Subject (' . pdf_str($b['subject']) . ') '
             . '/Keywords (' . pdf_str($b['keywords'] ?? '') . ') '
             . '/Creator (dev/make-fixtures.php) '
             . '/Producer (koreader_companion dev fixtures) '
             . '/CreationDate (D:20240101000000Z) >>',
    ];

    $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
    $offsets = [];
    foreach ($objects as $num => $body) {
        $offsets[$num] = strlen($pdf);
        $pdf .= "$num 0 obj\n$body\nendobj\n";
    }

    $xrefPos = strlen($pdf);
    $size = count($objects) + 1;
    $pdf .= "xref\n0 $size\n0000000000 65535 f \n";
    for ($i = 1; $i <= count($objects); $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= "trailer\n<< /Size $size /Root 1 0 R /Info 6 0 R >>\nstartxref\n$xrefPos\n%%EOF\n";

    file_put_contents($path, $pdf);
}
